[package]
name = "monorepo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.22", features = ["derive"] }
swc_common = "0.29.14"
sha2 = "0.10.6"
hex = "0.4.3"
swc_css = "0.140.3"