[package]
name = "monorepo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.1", features = ["derive"] }
swc_common = "0.29.27"
sha2 = "0.10.6"
hex = "0.4.3"
swc_css_codegen = "0.147.3"
swc_css_modules = "0.13.3"
swc_css_parser = "0.136.3"
serde_json = "1.0.91"
swc_atoms = "0.4.33"