l_french:
 SETTING_DEBUG_SAVES:0 "Nombre de sauvegardes de débogage"
 SETTING_TUTORIAL:0 "Didacticiel"
 SETTING_DISABLED_HINTS:0 "Conseils désactivés"
 SETTING_FOCUS_ON_COMBAT:0 "Centrer sur le combat"
 SETTING_TOOLTIP_DELAY:1 "Délai de l’infobulle"
 SETTING_TOOLTIP_DELAY_TOOLTIP:1 "#T $SETTING_TOOLTIP_DELAY$#!\nDéfinit le délai avant l’apparition des infobulles."
 SETTING_TOOLTIP_UNLOCK_TIME:0 "Délai de déverrouillage"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP:1 "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nDéfinit le délai avant que les infobulles soient déverrouillées."
 SETTING_TOOLTIP_LOCK_TIME:0 "Délai de verrouillage"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP:1 "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nDéfinit le délai avant le verrouillage des infobulles."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED:0 "Délai de verrouillage si ouvert"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP:1 "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nDéfinit le délai avant le verrouillage des infobulles lorsqu’une autre infobulle est déjà ouverte."
 # Audio
 SETTING_Sound_Effects:1 "Tous les effets sonores"
 SETTING_Sound_Effects_TOOLTIP:1 "#T Volume des effets sonores\n#!Règle le volume de tous les effets sonores."
 SETTING_Ambience:0 "Ambiance"
 SETTING_Ambience_TOOLTIP:1 "#T Volume d’ambiance\n#!Règle le volume des sons d’ambiance."
 SETTING_TOOLTIP_MODE:1 "Mode infobulle"
 SETTING_TOOLTIP_MODE_TOOLTIP:3 "#T $SETTING_TOOLTIP_MODE$#!\nDéfinit la façon dont les infobulles « se verrouillent » et activent les infobulles dans les infobulles."
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY:0 "Selon la souris"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_MOUSE_TENDENCY$#!\nLes infobulles sont automatiquement verrouillées jusqu’à ce que le curseur s’éloigne."
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION:0 "Selon l’action"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_LOCK_ON_ACTION$#!\nAppuyer sur le #V bouton du milieu de la souris#! pour verrouiller ou déverrouiller les infobulles."
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER:0 "Selon le temps"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_LOCK_ON_TIMER$#!\nLes infobulles sont verrouillées si le curseur ne bouge pas pendant un court instant. #weak (Paramètre par défaut)#!"
 SETTINGS_CATEGORY_INTERFACE_MISC:0 "Divers"
 SETTINGS_CATEGORY_TOOLTIPS:0 "Infobulles"
 SETTINGS_CATEGORY_SFX:0 "Effets sonores spécifiques"
 SETTINGS_CATEGORY_AUDIO_GENERAL:0 "Général"
 SETTINGS_CATEGORY_MAP_CONTROLS:0 "Contrôles de carte"
 SETTINGS_CATEGORY_SAVE_GAMES:0 "Sauvegardes"
 SETTINGS_CATEGORY_LANGUAGE:0 "Langue"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS:0 "Avancé - général"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS_MAP:0 "Avancé – carte"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS_Characters:0 "Avancé – personnages"
 SETTINGS_CATEGORY_GAME_PORTRAITS:0 "Portraits"
 SETTINGS_CATEGORY_MULTIPLAYER:0 "Multijoueur"
 SETTINGS_CATEGORY_MAP:0 "Carte"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS:0 "Afficher les maladies et les blessures"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS_TOOLTIP:0 "#T $SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS$#!\nDétermine si les graphismes des maladies et blessures sont visibles sur les portraits des personnages."
 SETTING_SHOW_NUDITY:0 "Afficher la nudité"
 SETTING_SHOW_NUDITY_TOOLTIP:0 "#T $SETTING_SHOW_NUDITY$#!\nDétermine si les personnages peuvent apparaître nus."
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE:0 "Panoramique de la Cour royale"
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE_TOOLTIP:0 "#T $SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE$#!\nDétermine si la caméra de la Cour royale doit effectuer un léger panoramique sur votre cour lorsqu’elle est inutilisée.\n\nSi les personnages animés sont désactivés, ce paramètre n’a aucun effet."
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION:0 "Transitions de la Cour royale"
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION_TOOLTIP:0 "#T $SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION$#!\nDétermine si la caméra de la Cour royale doit se déplacer doucement vers un nouvel emplacement.\n\nSi les personnages animés sont désactivés, ce paramètre n’a aucun effet."
 NEVER:0 "Jamais"
 MONTHLY:0 "Chaque mois"
 HALFYEAR:0 "Tous les 6 mois"
 YEARLY:0 "Chaque année"
 FIVE_YEAR:0 "Tous les 5 ans"
 SETTINGS_CATEGORY_TUTORIAL:0 "Didacticiel"
 SETTING_REACTIVE_TUTORIAL:1 "Afficher les conseils personnalisés"
 SETTING_REACTIVE_TUTORIAL_TOOLTIP:0 "#T $SETTING_REACTIVE_TUTORIAL$#!\nDétermine si le jeu doit afficher des conseils qui réagissent à la façon dont vous jouez. Utile pour les nouveaux joueurs de Crusader Kings III."
 SETTING_SHOW_SUGGESTIONS:0 "Afficher les suggestions"
 SETTING_SHOW_SUGGESTIONS_TOOLTIP:2 "#T $SETTING_SHOW_SUGGESTIONS$#!\nDéfinit si le jeu doit régulièrement suggérer des choses à faire. C’est utile pour les joueurs découvrant Crusader Kings III."
 RESET_REACTIVE_ADVICE:0 "Réinitialiser les conseils personnalisés"
 RESET_REACTIVE_ADVICE_TOOLTIP:1 "#T Réinitialiser les conseils personnalisés#!\nLes conseils personnalisés vus précédemment réapparaîtront."
 RESET_REACTIVE_ADVICE_CONFIRMATION_TITLE:0 "Réinitialiser les conseils personnalisés"
 RESET_REACTIVE_ADVICE_CONFIRMATION_TEXT:0 "Voulez-vous vraiment réinitialiser les conseils personnalisés ?"
 SETTING_ADVANCED_SHADERS:0 "Effets de nuanceur avancés"
 SETTING_ADVANCED_SHADERS_TOOLTIP:0 "#T Effets de nuanceur avancés\n#!Cette option permettra des effets de nuanceur avancés.\n\nLe fait de le désactiver peut augmenter les performances au risque d’aggraver la qualité de certains effets (par exemple, le terrain et l’eau)"
 SETTING_WINTER_PARTICLE_EFFECTS:0 "Effets des particules d’hiver"
 SETTING_WINTER_PARTICLE_EFFECTS_TOOLTIP:0 "#T $SETTING_WINTER_PARTICLE_EFFECTS$#!\nDétermine si les effets des particules sont visibles lorsque l’hiver est en cours dans une zone de la carte.\n\nLes désactiver peut améliorer les performances"
 SETTING_RESET_CAMERA_ROTATION:0 "Réinitialisation de la caméra"
 SETTING_RESET_CAMERA_ROTATION_TOOLTIP:0 "#T $SETTING_RESET_CAMERA_ROTATION$#!\nDétermine si la caméra doit automatiquement rétablir sa position par défaut après avoir été tournée par l’utilisateur."
 SETTING_COURT_SCENE_LOW_PRIORITY_CHARACTERS:0 "Personnages d’arrière-plan"
 SETTING_COURT_SCENE_LOW_PRIORITY_CHARACTERS_TOOLTIP:0 "#T $SETTING_RESET_CAMERA_ROTATION$#!\nDétermine si la Cour royale en 3D doit afficher des personnages d’arrière-plan moins importants."
 SETTING_MAP_HIGHLIGHT:0 "Mise en évidence du curseur"
 SETTING_MAP_HIGHLIGHT_TOOLTIP:0 "#T $SETTING_MAP_HIGHLIGHT$#!\nDétermine l’intensité de la mise en évidence du curseur sur la carte"
 BASED_ON_ZOOM_LEVEL:0 "Dynamique"
 ALWAYS_HIDE:0 "Toujours masquer"
 ALWAYS_SHOW:0 "Toujours afficher"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM:0 "Frontières côtières"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM_TOOLTIP:0 "#T $SETTING_HIDE_COAST_BORDER_ON_ZOOM$#!\nCette option permettra de contrôler à quel moment les frontières des pays côtiers doivent être indiquées.\nSi $BASED_ON_ZOOM_LEVEL$ alors elles seront masquées au niveau de zoom détaillé.\n\nChoisir $ALWAYS_SHOW$ ou $ALWAYS_HIDE$ peut augmenter les performances, mais les frontières des pays côtiers ne se masquent plus dynamiquement."
 SETTINGS_DISCARD_CHANGES:0 "Annuler les modifications"
