[package]
name = "rust-{{project-name}}"
version = "0.1.0"
authors = ["{{authors}}"]
edition = "2018"
resolver = "2"

[lib]
crate-type = ["staticlib"]

[profile.release]
opt-level = "s"

[profile.dev]
debug = true # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[dependencies]
{% if std %}esp-idf-sys = { version = "0.31.11", features = ["native"] }
{% else %}log = { version = "0.4", default-features = false }
esp-idf-sys = { version = "0.31.11", default-features = false, features = ["native", "panic_handler", "alloc_handler"] }
esp-idf-svc = { version = "0.43.1", default-features = false, features = ["alloc"] }{% endif %}

[build-dependencies]
embuild = "0.30.4"
anyhow = "1"
