---

name: CI
concurrency:
  group: concurrency-ci-${{ github.head_ref }}
  cancel-in-progress: true

on:   # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - versioned
  pull_request:
    branches:
      - main
      - versioned
  workflow_dispatch:

jobs:
  automerge:
    name: Auto-merge
    if: github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Fetch Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1.5.1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: 'Merge (if dependabot)'
        run: gh pr merge "$PR_URL" --auto --merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
  Test:
    # This runs on both push and PR – for
    # PR, we need to ensure tests pass,
    # but a PR cannot save a cache due to
    # security issues. Therefore, we run
    # post merge to create a cache that
    # can be picked up by future PRs.
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      # example copied from:
      # https://github.com/actions/cache/blob/04f198bf0b2a39f7230a4304bf07747a0bddf146/examples.md
      - name: Cache Bazel
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/bazel
          key: >
            ${{ runner.os }}-bazel-${{
            hashFiles('.bazelversion', '.bazelrc', 'WORKSPACE',
            'WORKSPACE.bazel', 'MODULE.bazel') }}
          restore-keys: |
            ${{ runner.os }}-bazel-
      - name: All tests
        # Use npx to try to generate only
        # bazel generated node_modules
        run: bazel test //...
