---

# See: /ci/README.md
#
#
# ```
# +-----------------------------+
# | 1.       PRESUBMIT          |
# +-----------------------------+
#   |
#   | All offline tests succeed.
#   |
#   |   - bazel test //...
#   v
# +-----------------------------+
# | 2.  AUTHORIZATION CHECK     |
# +-----------------------------+
#   | The next step will not run
#   | until one of the repo owners
#   | approves the commits.
#   |
#   v
# +-----------------------------+
# | 3.        SUBMIT            |
# +-----------------------------+
#   | Deploy actions that can
#   | be rolled back performed.
#   |
#   |  - Pulumi up
#   v
# +-----------------------------+
# | 3a.       ROLLBACK          |
# +-----------------------------+
#   | Upon failure of step 3,
#   | checkout origin/main,
#   | and re-perform SUBMIT.
#   x
# +-----------------------------+
# | 4.      POSTSUBMIT          |
# +-----------------------------+
#   | When (3) succeeds,
#   |
#   | Deploy actions that cannot
#   | be rolled back performed.
#   |
#   |  - Creating a GitHub release
#   |  - Uploading NPM packages
#   v
# +-----------------------------+
# | 5.         MERGE            |
# +-----------------------------+
#
# ```

name: CI

on:   # yamllint disable-line rule:truthy
  pull_request:
    branches:

      # presubmit
      - main
  push:
    branches:
      - main

  # manual triggering
  workflow_dispatch:


jobs:
  Presubmit:
    # this should stop presubmits being run even when there
    # is a successor commit in pull request.
    concurrency:
      group: concurrency-ci-${{ github.head_ref }}
      cancel-in-progress: true
    if: >
      github.event_name == 'pull_request'
      || github.event_name == 'workflow_dispatch'
    # Performs all offline testing.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      # example copied from:
      # https://github.com/actions/cache/blob/04f198bf0b2a39f7230a4304bf07747a0bddf146/examples.md
      - name: Cache Bazel
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/bazel
          key: >
            ${{ runner.os }}-bazel-${{
            hashFiles('.bazelversion', '.bazelrc', 'WORKSPACE',
            'WORKSPACE.bazel', 'MODULE.bazel') }}
          restore-keys: |
            ${{ runner.os }}-bazel-
      - name: Presubmit
        run: |
         bazel run //ci:presubmit -- --skip-pulumi-deploy
  Staging:
    # Pulumi doesn't like it when multiple deploys are attempted at once.
    # This is also enforced at the pulumi layer, but i'm sure github actions
    # would make me pay while that thread waits to acquire the lock.
    concurrency: pulumi_staging
    if: >
      github.event_name == 'pull_request'
      || github.event_name == 'workflow_dispatch'

    # Performs all offline testing.
    needs: Presubmit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      # example copied from:
      # https://github.com/actions/cache/blob/04f198bf0b2a39f7230a4304bf07747a0bddf146/examples.md
      - name: Cache Bazel
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/bazel
          key: >
            ${{ runner.os }}-bazel-${{
            hashFiles('.bazelversion', '.bazelrc', 'WORKSPACE',
            'WORKSPACE.bazel', 'MODULE.bazel') }}
          restore-keys: |
            ${{ runner.os }}-bazel-
      - name: Deploy to Staging
        run: |
         bazel run //ci:presubmit -- --dirty --skip-bazel-tests
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_SECRET }}
  Submit:
    concurrency: pulumi_production
    if: github.event_name == 'push'
    # Attempts to submit changes to production.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      # example copied from:
      # https://github.com/actions/cache/blob/04f198bf0b2a39f7230a4304bf07747a0bddf146/examples.md
      - name: Cache Bazel
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/bazel
          key: >
            ${{ runner.os }}-bazel-${{
            hashFiles('.bazelversion', '.bazelrc', 'WORKSPACE',
            'WORKSPACE.bazel', 'MODULE.bazel') }}
          restore-keys: |
            ${{ runner.os }}-bazel-
      - name: Submit
        # Use npx to try to generate only
        # bazel generated node_modules
        run: |
          bazel run //ci:submit
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_SECRET }}
  Postsubmit:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: Submit
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      # example copied from:
      # https://github.com/actions/cache/blob/04f198bf0b2a39f7230a4304bf07747a0bddf146/examples.md
      - name: Cache Bazel
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/bazel
          key: >
            ${{ runner.os }}-bazel-${{
            hashFiles('.bazelversion', '.bazelrc', 'WORKSPACE',
            'WORKSPACE.bazel', 'MODULE.bazel') }}
          restore-keys: |
            ${{ runner.os }}-bazel-
      - name: Postsubmit
        run: |
          bazel run //ci:postsubmit
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_SECRET }}
