
name: bazel
on:
  pull_request:
    branches: [ main ]
jobs:
  Test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Directly affected tests
        run: yarn test
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
      - name: All tests
        # Use npx to try to generate only
        # bazel generated node_modules
        run: yarn run bazelisk run test //...
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
