---


name: Renovate
concurrency:
  # if another instance of renovate is running,
  # do not attempt to run overlapping instances.
  group: renovate
on: # yamllint disable-line rule:truthy
  schedule:
    # The "*" (#42, asterisk) character has special semantics in YAML, so this
    # string has to be quoted.
    - cron: '0/15 * * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@f9c81dddc9b589e4e6ae0326d1e36f6bc415d230 # v39.2.4
        with:
          configurationFile: renovate.json
          token: ${{ secrets.GH_PAT }}
    env:
      LOG_LEVEL: 'debug'
