---


name: Renovate
concurrency:
  # if another instance of renovate is running,
  # do not attempt to run overlapping instances.
  group: renovate
on: # yamllint disable-line rule:truthy
  schedule:
    # The "*" (#42, asterisk) character has special semantics in YAML, so this
    # string has to be quoted.
    - cron: '0/15 * * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@17973eff4f1b66dc88786ea5490d902aaa274cbf # v40.2.9
        with:
          configurationFile: renovate.json
          token: ${{ secrets.GH_PAT }}
    env:
      LOG_LEVEL: 'debug'
