name: Sapling

on:
  merge_group:
    branches:
      - main
  pull_request:
    types:
      - edited
      - synchronize

jobs:
  merge_in_order:
    name: Merge Sapling Stacked Commits In Order
    runs-on: ubuntu-latest

    steps:
      - name: Check object
        run: |
          cat << OBJECT
          ${{ toJson(github) }}
          OBJECT

      - name: Check if this is a Sapling PR
        id: check_sapling_pr
        run: |
          if echo "${{ github.event.pull_request.body }}" |\
          grep -qF "[//]: # (BEGIN SAPLING FOOTER)"; then
            echo "is_sapling=true" >> $GITHUB_ENV
          else
            echo "is_sapling=false" >> $GITHUB_ENV
          fi

      - name: Always succeed for merge group
        if: ${{ github.event_name == 'merge_group' }}
        run: echo "This is a merge group run. Always succeed."

      - name: Success for non-Sapling PRs or valid Sapling PRs
        if: env.is_sapling == 'false' || github.event.pull_request.base.ref == 'main'
        run: echo "Go for it!"
