---

name: Version Management
concurrency:
  group: concurrency-versioning-${{ github.head_ref }}
  cancel-in-progress: true

on:   # yamllint disable-line rule:truthy
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  copy_to_versioned:
    name: Copy commits in main to versioned branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # Needed to allow an action to trigger another action.
          token: ${{ secrets.GH_PAT }}
      - name: Restore bazel cache
        uses: actions/cache@v3.0.11
        env:
          cache-name: bazel-cache
        with:
          path: |
            ~/.cache/bazelisk
            ~/.cache/bazel
          key: ${{ runner.os }}-${{ env.cache-name }}
      - name: Update versioned branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          echo "[auto-fix] " 1>&2
          git checkout versioned
          git merge main
          echo "[auto-fix] running fixers for all failing tests..." 1>&2
          TO_RUN=$(bazelisk test \
              --build_tests_only \
              --test_output=summary \
              --test_summary=terse \
              --test_tag_filters=fixable \
              --test_tag_filters=do_not_run_on_main \
              //... | \
              awk '{print $1}' | \
              sed 's/$/.fix/g' | \
              sed -n '/^\/\//p' || :)
          if [ -z "$TO_RUN" ]; then
            echo "Skipping fixers, none needed." 1>&2
          else
            echo "[auto fix] running: $TO_RUN"
            for command in $TO_RUN; do
              bazelisk run --subcommands --verbose_failures $command
            done
            git add -A
            git commit -am "Automatic fixes."
          fi
          echo "[auto-fix] ensuring tests are good..." 1>&2
          bazelisk test //... --test_tag_filters=do_not_run_on_main

          echo "[auto-fix] committing and submitting changes..." 1>&2
          git push
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
